{{- range $container := .Values.containers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl $container.name $ }}
spec:
  replicas: {{ $.Values.deployment.replicas }}
  selector:
    matchLabels:
      svc-name: {{ tpl $container.name $ }}
  template:
    metadata:
      labels:
        svc-name: {{ tpl $container.name $ }}
    spec:
      containers:
      - image: {{ $.Values.image.registry }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}
        name: {{ tpl $container.name $ }}
        ports:
          - containerPort: {{$.Values.service.port}}
        env:
          - name: WORLD
            valueFrom:
              configMapKeyRef:
                key: {{tpl $container.depRegion $}}
                name: {{ tpl $container.name $ }}
{{- end }} 